services:
  smee2:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./config.yml:/app/config.yml
    command:
        - --config=/app/config.yml

networks:
  default:
    external:
      name: sce
